#!/bin/bash

if [ -z "$1" ]; then
    echo "Please supply the RequestID to check its status. To get the list of pending requests run the command `pending`"
else
    echo $(wget --quiet --method GET --output-document - http://localhost:8080/Luzzu/v4/assessment/status/$1)
fi
